services:
  fuseki:
    image: stain/jena-fuseki:latest
    ports:
      - "3030:3030"
    volumes:
      - ./data:/staging:ro
      - fuseki-db:/fuseki
    environment:
      ADMIN_PASSWORD: "admin"
      FUSEKI_DATASET_1: "ds"
      TDB: "2"
      JVM_ARGS: "-Xmx1g"
    restart: unless-stopped

volumes:
  fuseki-db:
